function out_png = replot_offgrid_mse_pretty(result_mat_path)
% Replot off-grid benchmark MSE curve with cleaner paper-like styling.

data = load(result_mat_path, 'results');
results = data.results;

if isfield(results, 'narrowband') && isfield(results.narrowband, 'final')
    block = results.narrowband.final;
elseif isfield(results, 'wideband') && isfield(results.wideband, 'final')
    block = results.wideband.final;
else
    error('No final result block found in %s.', result_mat_path);
end

curves = block.curves;
methods = block.methods;
exp_cfg = block.exp_cfg;
styles = method_styles();

fig = figure('Color', 'w', 'Position', [120, 120, 980, 620]);
ax = axes(fig);
hold(ax, 'on');

for idx = 1:numel(methods)
    style = styles.(methods{idx}.short);
    plot(ax, curves.snr_values, curves.mean_mse_db(idx, :), ...
        'Color', style.color, ...
        'LineStyle', style.line_style, ...
        'LineWidth', style.line_width, ...
        'Marker', style.marker, ...
        'MarkerSize', style.marker_size, ...
        'MarkerFaceColor', style.marker_face, ...
        'MarkerEdgeColor', style.color, ...
        'DisplayName', methods{idx}.name);
end

grid(ax, 'on');
ax.GridColor = [0.85, 0.85, 0.85];
ax.GridAlpha = 0.8;
ax.MinorGridAlpha = 0.35;
ax.Box = 'on';
ax.LineWidth = 1.0;
ax.FontName = 'Times New Roman';
ax.FontSize = 15;
ax.XLim = [min(curves.snr_values), max(curves.snr_values)];
ax.XTick = curves.snr_values;

y_all = curves.mean_mse_db(:);
y_min = floor(min(y_all) / 5) * 5 - 2;
y_max = ceil(max(y_all) / 5) * 5 + 2;
if y_max - y_min < 20
    y_min = y_min - 3;
    y_max = y_max + 3;
end
ax.YLim = [y_min, y_max];

xlabel(ax, 'SNR (dB)', 'FontName', 'Times New Roman', 'FontSize', 18);
ylabel(ax, 'MSE (dB)', 'FontName', 'Times New Roman', 'FontSize', 18);
title(ax, sprintf('%s Off-grid MSE: %s', upper_first(exp_cfg.modality), exp_cfg.name), ...
    'Interpreter', 'none', ...
    'FontName', 'Times New Roman', ...
    'FontWeight', 'normal', ...
    'FontSize', 20);

lgd = legend(ax, 'Location', 'southwest', 'NumColumns', 2, 'FontSize', 12);
lgd.Box = 'on';
lgd.EdgeColor = [0.2, 0.2, 0.2];
lgd.Color = [1, 1, 1];

folder = fileparts(result_mat_path);
out_png = fullfile(folder, sprintf('%s_mse_only.png', exp_cfg.modality));
exportgraphics(fig, out_png, 'Resolution', 220);
close(fig);
end

function styles = method_styles()
styles.zdoa = struct( ...
    'color', [0.00, 0.00, 0.00], ...
    'line_style', '-', ...
    'line_width', 2.4, ...
    'marker', 'o', ...
    'marker_size', 8.0, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.music = struct( ...
    'color', [0.86, 0.37, 0.00], ...
    'line_style', '-', ...
    'line_width', 2.0, ...
    'marker', 's', ...
    'marker_size', 7.5, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.mvdr = struct( ...
    'color', [0.89, 0.67, 0.00], ...
    'line_style', '-', ...
    'line_width', 2.0, ...
    'marker', 'd', ...
    'marker_size', 7.5, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.beam_music = struct( ...
    'color', [0.41, 0.16, 0.64], ...
    'line_style', '--', ...
    'line_width', 2.0, ...
    'marker', '^', ...
    'marker_size', 8.0, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.beam_mvdr = struct( ...
    'color', [0.30, 0.64, 0.19], ...
    'line_style', '--', ...
    'line_width', 2.0, ...
    'marker', 'v', ...
    'marker_size', 8.0, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.power_bartlett = struct( ...
    'color', [0.20, 0.68, 0.92], ...
    'line_style', ':', ...
    'line_width', 2.4, ...
    'marker', '>', ...
    'marker_size', 8.0, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.power_nnls = struct( ...
    'color', [0.72, 0.12, 0.20], ...
    'line_style', '-.', ...
    'line_width', 2.2, ...
    'marker', 'h', ...
    'marker_size', 8.5, ...
    'marker_face', [1.00, 1.00, 1.00]);

styles.power_sbl = struct( ...
    'color', [0.78, 0.00, 0.62], ...
    'line_style', '-.', ...
    'line_width', 2.2, ...
    'marker', 'p', ...
    'marker_size', 9.0, ...
    'marker_face', [1.00, 1.00, 1.00]);
end

function out = upper_first(in)
out = in;
out(1) = upper(out(1));
end
